import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import { IoHomeOutline } from "react-icons/io5";
import { CiSearch } from "react-icons/ci";
import { MdOutlineExplore } from "react-icons/md";
import { FaRegUser } from "react-icons/fa";
import { IoIosAddCircleOutline } from "react-icons/io";
import { Button } from "@/components/ui/button";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex">
          <nav className="w-80 h-[100vh] border lg:block hidden px-5 pt-7 border-r-slate-200 lg:fixed ">
            <h1 className="text-2xl font-semibold">abdul book</h1>
            <ul className="flex flex-col gap-8 mt-8">
              <li>
                <Link href={"/"} className="flex gap-1 text-xl hover:scale-105 transition-all items-center"><IoHomeOutline />
                  home</Link>
              </li>
              <li >
                <Link className="flex gap-1 text-xl hover:scale-105 transition-all items-center" href={"/search"}><CiSearch />
                  seach</Link>
              </li>
              <li >
                <Link className="flex gap-1 text-xl hover:scale-105 transition-all items-center" href={"/explore"}><MdOutlineExplore />
explore</Link>
              </li>
              <li >
                <Link className="flex gap-1 text-xl hover:scale-105 transition-all items-center" href={"/add"}> <IoIosAddCircleOutline />
create</Link>
              </li>
              <li >
                <Link className="flex gap-1 text-xl hover:scale-105 transition-all items-center" href={"/profile"}> <FaRegUser />
profile</Link>
              </li>
            </ul>
            <Button variant={"default"} className="absolute bottom-8 ">Login</Button>
          </nav>
          <div className="lg:ml-80">
          {children}
          </div>

        </div>
      </body>
    </html>
  );
}
